name: CI

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install System Dependencies
        run: sudo apt-get install -y libegl1

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r src/kicad_xyce_plugin/requirements.txt

      - name: Lint
        run: |
          flake8 .

      - name: Unit Tests
        run: |
          coverage run --source=src -m pytest tests/
          coverage report -m
          coverage xml -o coverage.xml || true

      - name: Build
        run: |
          # git information
          export GIT_TAG_NAME=$(git tag --points-at HEAD 2>/dev/null | head -1)
          # release build only when version is available
          if [ -n "$GIT_TAG_NAME" ]; then
            # project version
            PROJECT_VERSION=$(echo "$GIT_TAG_NAME" | sed 's/^v//')
            # create package
            ./build/create-kicad-package.sh "$PROJECT_VERSION"
          fi
