name: C++ CI Workflow

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build & Test (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            build_enabled: true
          - os: windows-latest
            build_enabled: false
          - os: ubuntu-latest
            build_enabled: false

    runs-on: ${{ matrix.os }}

    env:
      VCPKG_BINARY_SOURCES: 'clear;files,${{ github.workspace }}/.vcpkg-cache,readwrite'

    steps:
      - name: Checkout repository
        if: ${{ matrix.build_enabled }}
        uses: actions/checkout@v7

      - name: Setup Ninja
        if: ${{ matrix.build_enabled }}
        uses: llvm/actions/install-ninja@main

      - name: Restore vcpkg binary cache
        if: ${{ matrix.build_enabled }}
        uses: actions/cache@v5
        with:
          path: ${{ github.workspace }}/.vcpkg-cache
          key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-

      - name: Setup vcpkg
        if: ${{ matrix.build_enabled }}
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'

      - name: Configure CMake
        if: ${{ matrix.build_enabled }}
        run: |
          cmake --preset vcpkg

      - name: Build C++ Target
        if: ${{ matrix.build_enabled }}
        run: |
          cmake --build --preset vcpkg

      # - name: Run C++ Tests
      #   if: ${{ matrix.build_enabled }}
      #   run: |
      #     ./.build-debug/tests/kicad-xyce-plugin-tests
